apiVersion: batch/v1
kind: Job
metadata:
  name: sparkplayground
spec:
  template:
    metadata:
      name: sparkplayground
    spec:
      containers:
        - name: sparkplayground
          image: ubuntu
          command: ["bash"]
          args: ["-c",  "current=0; max=70; echo 1; echo 2; for((i=3;i<=max;)); do for((j=i-1;j>=2;)); do if [  `expr $i % $j` -ne 0 ] ; then current=1; else current=0; break; fi; j=`expr $j - 1`; done; if [ $current -eq 1 ] ; then echo $i; fi; i=`expr $i + 1`; done"]
      restartPolicy: Never