apiVersion: batch/v1
kind: Job
metadata:
  name: sparkplayground
spec:
  template:
    metadata:
      name: sparkplayground
    spec:
      dnsPolicy: Default
      containers:
        - name: sparkplayground
          image: sustain/sparkplayground
          imagePullPolicy: Always
          ports:
          - containerPort: 50052
          - containerPort: 9079
          env:
          - name: NODE_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
      restartPolicy: Never