apiVersion: v1
kind: Pod
metadata:
  name: sparkplayground
spec:
  dnsPolicy: Default
  restartPolicy: Never
  containers:
    - name: sparkplayground
      image: sustain/sparkplayground
      imagePullPolicy: Always
      # command: [ "/bin/bash", "-c", "--" ]
      # args: [ "while true; do sleep 30; done;" ]
      ports:
      - containerPort: 50052
      - containerPort: 50053
      - containerPort: 4040
      - containerPort: 9079
      env:
      - name: NODE_HOSTNAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    - name: mongos-router
      image: mongo:4.4.4
      imagePullPolicy: Always
      command: [ 'sh', '-c', 'mongos --configdb cfgrs/lattice-147:27017,lattice-148:27017,lattice-149:27017 --bind_ip_all --port 27018' ]
      ports:
      - containerPort: 27018
